# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    strategy:
      matrix:
        include:
          - arch: msp-G2553
            fqbn: 'energia:msp430:MSP-EXP430G2553LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-G2452
            fqbn: 'energia:msp430:MSP-EXP430G2452LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-F5529
            fqbn: 'energia:msp430:MSP-EXP430F5529LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-FR4133
            fqbn: 'energia:msp430:MSP-EXP430FR4133LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-FR6989
            fqbn: 'energia:msp430:MSP-EXP430FR6989LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-FR2433
            fqbn: 'energia:msp430:MSP-EXP430FR2433LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-FR5969
            fqbn: 'energia:msp430:MSP-EXP430FR5969LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'

    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/arduino-compile-sketches.yml@main
    with:
      message: ${{ inputs.message }}
      copyfile: 
      fqbn: ${{ matrix.fqbn }}
      platform-name: ${{ matrix.platform-name }}
      platform-sourceurl: ${{ matrix.platform-sourceurl }}
      platform-version: latest
      libraries: |            
        - source-path: ./

