# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'energia:msp430:MSP-EXP430G2553LP'
          platforms: |
            - name: 'energia:msp430'
              version: latest
              source-url: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_G2_107_index.json'
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
      # Now trigger builds on repos dependent on this library
      - name: Trigger build on Outdoor-Weather-Sensor
        run: |
          curl -X POST https://api.github.com/repos/Andy4495/Outdoor-Weather-Sensor/actions/workflows/arduino-compile-sketches.yml/dispatches -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.FORCE_REBUILD }}" -d '{"ref":"main", "inputs":{"message":"Triggered by ${{ github.repository }} from ${{ github.workflow }} workflow run number ${{ github.run_number }}"}}'
      - name: Trigger build on MSP430LowPowerTempSensor
        run: |
          curl -X POST https://api.github.com/repos/Andy4495/MSP430LowPowerTempSensor/actions/workflows/arduino-compile-sketches.yml/dispatches -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.FORCE_REBUILD }}" -d '{"ref":"main", "inputs":{"message":"Triggered by ${{ github.repository }} from ${{ github.workflow }} workflow run number ${{ github.run_number }}"}}'
      - name: Trigger build on Wireless-DS18B20-Temp-Sensor
        run: |
          curl -X POST https://api.github.com/repos/Andy4495/Wireless-DS18B20-Temp-Sensor/actions/workflows/arduino-compile-sketches.yml/dispatches -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.FORCE_REBUILD }}" -d '{"ref":"main", "inputs":{"message":"Triggered by ${{ github.repository }} from ${{ github.workflow }} workflow run number ${{ github.run_number }}"}}'
      - name: Trigger build on Sensor-Repeater
        run: |
          curl -X POST https://api.github.com/repos/Andy4495/Sensor-Repeater/actions/workflows/arduino-compile-sketches.yml/dispatches -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.FORCE_REBUILD }}" -d '{"ref":"main", "inputs":{"message":"Triggered by ${{ github.repository }} from ${{ github.workflow }} workflow run number ${{ github.run_number }}"}}'
      - name: Trigger build on MSP430TempSensorWithDisplay
        run: |
          curl -X POST https://api.github.com/repos/Andy4495/MSP430TempSensorWithDisplay/actions/workflows/arduino-compile-sketches.yml/dispatches -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.FORCE_REBUILD }}" -d '{"ref":"main", "inputs":{"message":"Triggered by ${{ github.repository }} from ${{ github.workflow }} workflow run number ${{ github.run_number }}"}}'

